project_id = "qmehdnkqslglrbcnoswh"

[functions.auth-login]
verify_jwt = false

[functions.auth-signup]
verify_jwt = false

[functions.auth-change-password]
verify_jwt = false

[functions.auth-reset-password]
verify_jwt = false

[functions.auth-set-security-question]
verify_jwt = false

[functions.monitors]
verify_jwt = false

[functions.avatars]
verify_jwt = false
